import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReCaptchaWrapper from "@/components/ReCaptchaWrapper";
import {Layout} from "@/components/Layout";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Deveteria is a software development and consulting company",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {/* Wrap children in the client-side Recaptcha provider */}
        <ReCaptchaWrapper>
            <Layout>
             {children}
            </Layout>
        </ReCaptchaWrapper>

        </body>
        </html>
    );
}
